import { LinkedList } from './LinkedList'

describe('LinkedList tests', () => {
  it('add', () => {
    const linkedList = new LinkedList<number>()
    linkedList.add(1)
    linkedList.add(2)
    linkedList.add(3)
    expect(linkedList.size()).toEqual(3)
    expect(Array.from(linkedList.values())).toStrictEqual([1, 2, 3])
  })
  it('findByIndex', () => {
    const linkedList = new LinkedList<number>()
    linkedList.add(1)
    linkedList.add(2)
    linkedList.add(3)
    expect(linkedList.size()).toEqual(3)
    // console.log(Array.from(linkedList.values()))
    expect(linkedList.findByIndex(0)?.data).toEqual(1)
    expect(linkedList.findByIndex(1)?.data).toEqual(2)
    expect(linkedList.findByIndex(2)?.data).toEqual(3)
  })
  it('add at specified position', () => {
    const linkedList = new LinkedList<number>()
    linkedList.add(1)
    linkedList.add(2, 3) // 索引大于链表长度
    linkedList.add(3)
    linkedList.add(2, 2)
    expect(linkedList.size()).toEqual(3)
    expect(Array.from(linkedList.values())).toStrictEqual([1, 3, 2])
  })
  describe('reverse cases', () => {
    it('case 1', () => {
      const linkedList = new LinkedList()
      linkedList.add(1)
      linkedList.add(2)
      linkedList.add(3)
      linkedList.add(4)
      linkedList.add(5)
      linkedList.reverse()
      expect(Array.from(linkedList.values())).toStrictEqual([5, 4, 3, 2, 1])
    })
    it('case 2', () => {
      const linkedList = new LinkedList()
      linkedList.add(1)
      linkedList.add(2)
      linkedList.reverse()
      expect(Array.from(linkedList.values())).toStrictEqual([2, 1])
    })
    it('case 3', () => {
      const linkedList = new LinkedList()
      linkedList.add(1)
      linkedList.reverse()
      expect(Array.from(linkedList.values())).toStrictEqual([1])
    })
    it('case 4', () => {
      const linkedList = new LinkedList()
      linkedList.reverse()
      expect(Array.from(linkedList.values())).toStrictEqual([])
    })
  })

  // describe('indexOf', () => {
  //   it('should return the right index', () => {
  //     const linkedList = new LinkedList<number>()
  //     linkedList.add(1)
  //     linkedList.add(2)
  //     linkedList.add(3)
  //     linkedList.add(4)
  //     linkedList.add(5)
  //     expect(linkedList.indexOf(3)).toEqual(3)
  //   })
  //   it('should return -1 when no matched value', () => {
  //     const linkedList = new LinkedList<number>()
  //     linkedList.add(1)
  //     linkedList.add(2)
  //     linkedList.add(3)
  //     linkedList.add(4)
  //     linkedList.add(5)
  //     expect(linkedList.indexOf(9)).toEqual(-1)
  //   })
  //   it('should return -1 when LinkedList is empty', () => {
  //     const linkedList = new LinkedList()
  //     expect(linkedList.indexOf(9)).toEqual(-1)
  //   })
  // })
  // describe('search', () => {
  //   it('should return the index when the first item matched the search condition', () => {
  //     const linkedList = new LinkedList<number>()
  //     linkedList.add(1)
  //     linkedList.add(2)
  //     linkedList.add(3)
  //     linkedList.add(4)
  //     linkedList.add(5)
  //     expect(linkedList.search((data) => data === 5)).toEqual(5)
  //   })
  //   it('should return -1 when no item match the search condition', () => {
  //     const linkedList = new LinkedList<number>()
  //     linkedList.add(1)
  //     linkedList.add(2)
  //     linkedList.add(3)
  //     linkedList.add(4)
  //     linkedList.add(5)
  //     expect(linkedList.search((data) => data === 9)).toEqual(-1)
  //   })
  // })
  // describe('traverse', () => {
  //   const linkedList = new LinkedList<number>()
  //   linkedList.add(1)
  //   linkedList.add(2)
  //   linkedList.add(3)
  //   linkedList.add(4)
  //   let sum = 0
  //   linkedList.traverse((node) => {
  //     // console.log(node)
  //     sum += node.data
  //   })
  //   expect(sum).toEqual(10)
  // })
  // describe('remove', () => {
  //   const linkedList = new LinkedList<number>()
  //   linkedList.add(1)
  //   linkedList.add(2)
  //   linkedList.add(3)
  //   linkedList.add(4)
  //   linkedList.remove(2)
  //   linkedList.remove(4)
  //   expect(Array.from(linkedList.values())).toMatchObject([1, 3])
  // })
})
